/* ks_config.h - (generated by ./configure). Please rerun ./configure, and do NOT modify this file!
 *
 * Configure Script Ran:
 * $ ./configure
 *
 * Vars:
 * CC            = cc
 * CFLAGS        = -O3 -std=c99
 * LDFLAGS       = 
 * PREFIX        = /usr/local
 * PWD           = /home/cade/projects/kscript
 * V             = [0, 0, 1]
 * BUILD_TYPE    = release
 * MODULES       = ['modules/m', 'modules/nx']
 *
 *
 * Misc.:
 * sys.platform  = linux
 *
 */

#pragma once
#ifndef KS_CONFIG_H__
#define KS_CONFIG_H__

#ifdef __cplusplus
extern "C" {
#endif


/* VERSION */

#define KS_VERSION_MAJOR 0
#define KS_VERSION_MINOR 0
#define KS_VERSION_PATCH 1

#define KS_BUILD_STR "release"
#define KS_BUILD_RELEASE



/* platform info */

#define KS_PLATFORM_NAME "linux"


/* misc. defines */

#define KS__LINUX


/* warnings */




#ifdef __cplusplus
}
#endif

#endif /* KS_CONFIG_H__ */

