/* ks_config.h - (generated by ./configure). Please rerun ./configure, and do NOT modify this file!
*
* Configure Script Ran:
* $ ./configure --prefix=./prefix
*
* Vars:
* CC            = cc
* CFLAGS        = -O3 -std=c99 -I/usr/include/readline 
* LDFLAGS       = 
* PREFIX        = /home/cade/projects/kscript/prefix
* DESTDIR       = 
* PWD           = /home/cade/projects/kscript
* V             = [0, 0, 1]
* BUILD_TYPE    = release
* MODULES       = ['modules/sock', 'modules/sys', 'modules/libc', 'modules/cnk', 'modules/getarg', 'modules/mm', 'modules/nx', 'modules/req', 'modules/m']
*
*
* Misc.:
* sys.platform  = linux
*
*/

#pragma once
#ifndef KS_CONFIG_H__
#define KS_CONFIG_H__

#ifdef __cplusplus
extern "C" {
#endif


/* VERSION */

#define KS_VERSION_MAJOR 0
#define KS_VERSION_MINOR 0
#define KS_VERSION_PATCH 1

#define KS_BUILD_STR "release"
#define KS_BUILD_RELEASE


/* platform info */

#define KS_PLATFORM_NAME "linux"

#define KS_API_EXPORT 
#define KS_API_IMPORT 

#ifdef KS_BUILD
#define KS_API KS_API_EXPORT
#else
#define KS_API KS_API_IMPORT
#endif

#define KS_PREFIX "/home/cade/projects/kscript/prefix"

/* attributes */



#if defined(__GNUC__)
#define __KS_WARN_UNUSED__ __attribute__ ((warn_unused_result))
#else 
#define __KS_WARN_UNUSED__
#endif



/* modules */

#define KS_HAVE_MODULE_SOCK
#define KS_HAVE_MODULE_SYS
#define KS_HAVE_MODULE_LIBC
#define KS_HAVE_MODULE_CNK
#define KS_HAVE_MODULE_GETARG
#define KS_HAVE_MODULE_MM
#define KS_HAVE_MODULE_NX
#define KS_HAVE_MODULE_REQ
#define KS_HAVE_MODULE_M


/* misc. defines */

#define KS_HAVE_GMP
#define KS_HAVE_READLINE
#define KS_HAVE_CURL
#define KS_HAVE_GLFW3
#define KS_HAVE_LIBAV
#define KS_HAVE_FFI
#define KS_HAVE_FFTW3
#define SIZEOF_INT32_T 4
#define SIZEOF_INT64_T 8
#define SIZEOF_SIGNED_LONG 8
#define SIZEOF_UNSIGNED_LONG 8
#define KS__LINUX
#define KS_SHARED_END "so"
#define KS_STATIC_END "a"


/* warnings */





/* extra */

#define _POSIX_C_SOURCE 199309L


#ifdef __cplusplus
}
#endif

#endif /* KS_CONFIG_H__ */

