# kscript .travis.yml

# C language, but call it generic because its a custom build process
language: generic

# use Python3.7
python: 3.7

# supported OSes
os:
  - linux
#  - osx

# Ubuntu distribution
dist: xenial

# install dependencies
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo apt -y update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo apt -y install libgmp-dev libreadline-dev libcurl4-openssl-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "osx"    ]; then brew install python gmp readline curl; fi

jobs:
  include:
    - stage: configure
      script: ./configure --with-readline --with-curl --with-gmp
    - stage: build
      script: make -j8
    - stage: tar
      script: tar -czvf kscript-build-$TRAVIS_COMMIT.tar.gz lib include bin
    - stage: upload
      script: curl --upload-file kscript-build-$TRAVIS_COMMIT.tar.gz https://transfer.sh/kscript-build-$TRAVIS_COMMIT.tar.gz


