# kscript .travis.yml

# C language, but this is required for the correct versions of stuff
language: python

# use Python3.7
python: 3.7
env: PYTHON_VERSION=3.7.1

# supported OSes
os:
  - linux
#  - osx

# Ubuntu distribution
dist: xenial

# install dependencies
install:
  - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo apt -y update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo apt -y install libgmp-dev libreadline-dev libcurl4-openssl-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "osx"    ]; then brew install python gmp readline curl; fi

script: python3.7 ./configure --with-readline --with-curl --with-gmp && make -j8 && tar -czvf kscript-build-$TRAVIS_COMMIT.tar.gz lib include bin && curl --upload-file kscript-build-$TRAVIS_COMMIT.tar.gz https://transfer.sh/kscript-build-$TRAVIS_COMMIT.tar.gz


