.TH KSCRIPT 1
.SH NAME
kscript \- a dynamic, interpreted, duck-typed language with a large and feature-rich standard library, meant for application development, utilities, and more
.SH SYNOPSIS
.B kscript
[ \fB\-h\fR ] [ \fB\-V\fR ] [ \fB\-v\fR[vv] ]
[ \fB\-e\fR EXPR | \fIfile\fR ] [args...]
.SH DESCRIPTION
.B kscript
is the main binary for running kscript-language code (see )
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Prints a help/usage message that describes usage and functionality, then exits
.TP
.BR \-V ", " \-\-version
Prints out the version and build information, then exits
.TP
.BR \-v[vv]
Increase the verbosity of the program. Default is 'WARN', then the levels go: 'INFO', 'DEBUG', 'TRACE'.
\'TRACE' level of verbosity may be disabled on some release builds, for speed reasons
.TP
.BR \-e ", " \-\-expr=[EXPR]
Compiles and runs the argument, treating it as kscript code
.SH AUTHOR
Cade Brown: <brown.cade@gmail.com>, under ChemicalDevelopment: https://chemicaldevelopment.us
.SH LICENSE
The license of this software is the GNU GPL v3. 

Please see https://www.gnu.org/licenses/gpl-3.0.txt for a copy, or see the one that was distributed with this package